### PR TITLE
Apple Code Signing and Notarization

### PR DESCRIPTION
**Pull request by mattahorton**

### CODE REVIEW

**Comment by mikedickey** [comment]
Is there a way to split this out into a separate workflow file ("jacktriplabs"?) to help insulate us from upstream change conflicts?

**Comment by mattahorton** [comment]
> Is there a way to split this out into a separate workflow file ("jacktriplabs"?) to help insulate us from upstream change conflicts?

Yep. I'll get that done. Would be nice to put the Windows stuff in there too when I get to it.

**Comment by mattahorton** [comment]
@mikedickey let these tests run, and we should be good.

**Comment by mikedickey** [comment]
> > Is there a way to split this out into a separate workflow file ("jacktriplabs"?) to help insulate us from upstream change conflicts?
> 
> Yep. I'll get that done. Would be nice to put the Windows stuff in there too when I get to it.

I was hoping there was a way we could avoid duplicating anything from the jacktrip yml and have jacktriplabs only be the extra signing steps? If not, what you had before may be better because otherwise we will have to manually be merging updates every time we pull (versus letting git do its best to handle that for us).

Can we just reuse artifacts produced by the jacktrip steps, or do we have to fundamentally change the way things are built to support signing?

**Comment by mattahorton** [comment]
> > > Is there a way to split this out into a separate workflow file ("jacktriplabs"?) to help insulate us from upstream change conflicts?
> > 
> > 
> > Yep. I'll get that done. Would be nice to put the Windows stuff in there too when I get to it.
> 
> I was hoping there was a way we could avoid duplicating anything from the jacktrip yml and have jacktriplabs only be the extra signing steps? If not, what you had before may be better because otherwise we will have to manually be merging updates every time we pull (versus letting git do its best to handle that for us).
> 
> Can we just reuse artifacts produced by the jacktrip steps, or do we have to fundamentally change the way things are built to support signing?

Ah. Looks like it's possible. That's going to be more work, but I'll make it happen.

**Comment by mattahorton** [comment]
@mikedickey I'm having trouble getting Github to recognize the new workflow. It worked for a bit when it was named the same thing as the build workflow, but now it's broken.

According to documentation, in order to run either `workflow_run` or `workflow_dispatch` workflows, the workflow file has to be present in the default branch. In this case that is `main`. 

I believe this new workflow should sign the Mac bundle and installer as-is. But I can't prove that before merging apparently. I could also simply move my work to a _job_ that runs after the build job in the build workflow. That would guarantee we could test it.

I don't like the idea of merging everything over to main just yet. Thoughts?

**Comment by mattahorton** [comment]
Alright. Right now, this all runs as a follow-up job, but the same job exists in a separate workflow that won't run until this is in main. 

I'm good to merge to dev if you are @mikedickey

**Review by mikedickey — APPROVED** [review]

**Pull request merged**
